// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CODE_BLUE_PANEL_H
#define UI_CODE_BLUE_PANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Code_Blue_Panel
extern void ui_Code_Blue_Panel_screen_init(void);
extern void ui_Code_Blue_Panel_screen_destroy(void);
extern void ui_Code_Blue_Panel_screen_relocalize(void);
extern lv_obj_t * ui_Code_Blue_Panel;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label21;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Code_Blue_Panel;
extern lv_obj_t * uic_Panel8;
extern lv_obj_t * uic_Label19;
extern lv_obj_t * uic_Label20;
extern lv_obj_t * uic_Button10;
extern lv_obj_t * uic_Label21;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

