// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CALL_PANEL_H
#define UI_CALL_PANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Call_Panel
extern void ui_Call_Panel_screen_init(void);
extern void ui_Call_Panel_screen_destroy(void);
extern void ui_Call_Panel_screen_relocalize(void);
extern lv_obj_t * ui_Call_Panel;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Call_Panel;
extern lv_obj_t * uic_Panel7;
extern lv_obj_t * uic_Label15;
extern lv_obj_t * uic_Label16;
extern lv_obj_t * uic_Button8;
extern lv_obj_t * uic_Label17;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

