// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label17;
lv_obj_t * uic_Button8;
lv_obj_t * uic_Label16;
lv_obj_t * uic_Label15;
lv_obj_t * uic_Panel7;
lv_obj_t * uic_Call_Panel;
lv_obj_t * ui_Call_Panel = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label17 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Call_Panel_screen_init(void)
{
    ui_Call_Panel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Call_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Call_Panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Call_Panel);
    lv_obj_set_width(ui_Panel7, 632);
    lv_obj_set_height(ui_Panel7, 538);
    lv_obj_set_x(ui_Panel7, 2);
    lv_obj_set_y(ui_Panel7, -8);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Call_Panel);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -1);
    lv_obj_set_y(ui_Label15, -100);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Nurse station notified\nPlease wait for assistance ");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Call_Panel);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 2);
    lv_obj_set_y(ui_Label16, 53);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Status: ACTIVE");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_Call_Panel);
    lv_obj_set_width(ui_Button8, 167);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, 13);
    lv_obj_set_y(ui_Button8, 197);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Call_Panel);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 13);
    lv_obj_set_y(ui_Label17, 199);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Cancel Call");

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    uic_Call_Panel = ui_Call_Panel;
    uic_Panel7 = ui_Panel7;
    uic_Label15 = ui_Label15;
    uic_Label16 = ui_Label16;
    uic_Button8 = ui_Button8;
    uic_Label17 = ui_Label17;

}

void ui_Call_Panel_screen_destroy(void)
{
    if(ui_Call_Panel) lv_obj_del(ui_Call_Panel);

    // NULL screen variables
    uic_Call_Panel = NULL;
    ui_Call_Panel = NULL;
    uic_Panel7 = NULL;
    ui_Panel7 = NULL;
    uic_Label15 = NULL;
    ui_Label15 = NULL;
    uic_Label16 = NULL;
    ui_Label16 = NULL;
    uic_Button8 = NULL;
    ui_Button8 = NULL;
    uic_Label17 = NULL;
    ui_Label17 = NULL;

}

void ui_Call_Panel_screen_relocalize(void)
{
    // label widgets on screen

}
