// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>

void GOES_DARK(lv_event_t * e);
void on_in_progress_click(lv_event_t * e);
void ui_apply_dark_mode(void);
bool ui_is_dark_mode_enabled(void);
void ui_clear_notification(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
