// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_EMERGENCY_PANEL_H
#define UI_EMERGENCY_PANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Emergency_Panel
extern void ui_Emergency_Panel_screen_init(void);
extern void ui_Emergency_Panel_screen_destroy(void);
extern void ui_Emergency_Panel_screen_relocalize(void);
extern void ui_event_Emergency_Panel(lv_event_t * e);
extern lv_obj_t * ui_Emergency_Panel;
extern lv_obj_t * ui_Panel6;
extern void ui_event_Label14(lv_event_t * e);
extern lv_obj_t * ui_Label14;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Emergency_Panel;
extern lv_obj_t * uic_Panel6;
extern lv_obj_t * uic_Label14;
extern lv_obj_t * uic_Button11;
extern lv_obj_t * uic_Label22;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

