// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "alert_audio.h"

lv_obj_t * uic_Label22;
lv_obj_t * uic_Button11;
lv_obj_t * uic_Label14;
lv_obj_t * uic_Panel6;
lv_obj_t * uic_Emergency_Panel;
lv_obj_t * ui_Emergency_Panel = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label27 = NULL;
// event funtions
void ui_event_Emergency_Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Blink_Animation(ui_Emergency_Panel, 5000);
    }
}

void ui_event_Label14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        Blink_Animation(ui_Label14, 0);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        nurse_audio_stop();
        ui_clear_notification();
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Emergency_Panel_screen_init(void)
{
    ui_Emergency_Panel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Emergency_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Emergency_Panel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Emergency_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_apply_dark_mode();

    ui_Panel6 = lv_obj_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Panel6, 575);
    lv_obj_set_height(ui_Panel6, 554);
    lv_obj_set_x(ui_Panel6, 3);
    lv_obj_set_y(ui_Panel6, -5);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -5);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Alert Message Sent!");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Button11, 167);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, -135);
    lv_obj_set_y(ui_Button11, 172);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -138);
    lv_obj_set_y(ui_Label22, 172);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "In Progress");

    ui_Button1 = lv_btn_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Button1, 167);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 135);
    lv_obj_set_y(ui_Button1, 171);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Emergency_Panel);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 135);
    lv_obj_set_y(ui_Label27, 171);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Resolved");

    lv_obj_add_event_cb(ui_Button11, on_in_progress_click, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label14, ui_event_Label14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Emergency_Panel, ui_event_Emergency_Panel, LV_EVENT_ALL, NULL);
    uic_Emergency_Panel = ui_Emergency_Panel;
    uic_Panel6 = ui_Panel6;
    uic_Label14 = ui_Label14;
    uic_Button11 = ui_Button11;
    uic_Label22 = ui_Label22;

}

void ui_Emergency_Panel_screen_destroy(void)
{
    if(ui_Emergency_Panel) lv_obj_del(ui_Emergency_Panel);

    // NULL screen variables
    uic_Emergency_Panel = NULL;
    ui_Emergency_Panel = NULL;
    uic_Panel6 = NULL;
    ui_Panel6 = NULL;
    uic_Label14 = NULL;
    ui_Label14 = NULL;
    uic_Button11 = NULL;
    ui_Button11 = NULL;
    uic_Label22 = NULL;
    ui_Label22 = NULL;
    ui_Button1 = NULL;
    ui_Label27 = NULL;

}

void ui_Emergency_Panel_screen_relocalize(void)
{
    // label widgets on screen

}
