// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_Screen1_screen_relocalize(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image2;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label25;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Panel1;
extern lv_obj_t * uic_Panel2;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Panel3;
extern lv_obj_t * uic_Label2;
extern lv_obj_t * uic_Label4;
extern lv_obj_t * uic_Panel5;
extern lv_obj_t * uic_Label6;
extern lv_obj_t * uic_Label5;
extern lv_obj_t * uic_Label7;
extern lv_obj_t * uic_Button2;
extern lv_obj_t * uic_Label13;
extern lv_obj_t * uic_Switch1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

