// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_Screen2_screen_relocalize(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button4;
extern lv_obj_t * uic_Button3;
extern lv_obj_t * uic_Button5;
extern lv_obj_t * uic_Button6;
extern lv_obj_t * uic_Button7;
extern lv_obj_t * uic_Label8;
extern lv_obj_t * uic_Label9;
extern lv_obj_t * uic_Label10;
extern lv_obj_t * uic_Label11;
extern lv_obj_t * uic_Label12;
extern lv_obj_t * uic_Button9;
extern lv_obj_t * uic_Label18;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

