// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TOILET_EMERGENCY_PANEL_H
#define UI_TOILET_EMERGENCY_PANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Toilet_Emergency_Panel
extern void ui_Toilet_Emergency_Panel_screen_init(void);
extern void ui_Toilet_Emergency_Panel_screen_destroy(void);
extern void ui_Toilet_Emergency_Panel_screen_relocalize(void);
extern lv_obj_t * ui_Toilet_Emergency_Panel;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label23;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label24;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Toilet_Emergency_Panel;
extern lv_obj_t * uic_Panel9;
extern lv_obj_t * uic_Label23;
extern lv_obj_t * uic_Button12;
extern lv_obj_t * uic_Label24;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

