// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label24;
lv_obj_t * uic_Button12;
lv_obj_t * uic_Label23;
lv_obj_t * uic_Panel9;
lv_obj_t * uic_Toilet_Emergency_Panel;
lv_obj_t * ui_Toilet_Emergency_Panel = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label24 = NULL;
// event funtions
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Toilet_Emergency_Panel_screen_init(void)
{
    ui_Toilet_Emergency_Panel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Toilet_Emergency_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Toilet_Emergency_Panel, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Toilet_Emergency_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Toilet_Emergency_Panel);
    lv_obj_set_width(ui_Panel9, 632);
    lv_obj_set_height(ui_Panel9, 538);
    lv_obj_set_x(ui_Panel9, 2);
    lv_obj_set_y(ui_Panel9, -8);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Toilet_Emergency_Panel);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 8);
    lv_obj_set_y(ui_Label23, -41);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Bathroom assistance requested\nStaff have been notified\n\n\n\n\n\n\nStatus: ACTIVE");
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Toilet_Emergency_Panel);
    lv_obj_set_width(ui_Button12, 167);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, 13);
    lv_obj_set_y(ui_Button12, 197);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Toilet_Emergency_Panel);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 13);
    lv_obj_set_y(ui_Label24, 199);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Cancel Call");

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    uic_Toilet_Emergency_Panel = ui_Toilet_Emergency_Panel;
    uic_Panel9 = ui_Panel9;
    uic_Label23 = ui_Label23;
    uic_Button12 = ui_Button12;
    uic_Label24 = ui_Label24;

}

void ui_Toilet_Emergency_Panel_screen_destroy(void)
{
    if(ui_Toilet_Emergency_Panel) lv_obj_del(ui_Toilet_Emergency_Panel);

    // NULL screen variables
    uic_Toilet_Emergency_Panel = NULL;
    ui_Toilet_Emergency_Panel = NULL;
    uic_Panel9 = NULL;
    ui_Panel9 = NULL;
    uic_Label23 = NULL;
    ui_Label23 = NULL;
    uic_Button12 = NULL;
    ui_Button12 = NULL;
    uic_Label24 = NULL;
    ui_Label24 = NULL;

}

void ui_Toilet_Emergency_Panel_screen_relocalize(void)
{
    // label widgets on screen

}
